# Generated by Django 2.2.22 on 2022-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('postion', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('attendance', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('check', models.BooleanField()),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.ForeignKey(on_delete='cascade', to='myapi.Hero')),
            ],
        ),
    ]
